repos:

- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    language: system

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
    exclude: '^(docs/)|(examples/)|(utils/fastentrypoints.py)'

- repo: local
  hooks:

  - id: prospector
    name: prospector
    entry: prospector
    types: [file, python]
    language: system
    exclude: '^(docs/)|(examples/)|(utils/fastentrypoints.py)'

  - id: version-number
    name: Check version numbers
    entry: python ./utils/validate_version_consistency.py
    language: system
    files: >-
      (?x)^(
        setup.json|
        utils/validate_version_consistency.py|
        aiida_testing/__init__.py
      )$
    pass_filenames: false
