repos:

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    types: [python]
    args: ['-i']
    additional_dependencies: [toml]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --show-fixes]

- repo: local
  hooks:

  -  id: mypy
     name: mypy
     entry: mypy
     args: [--config-file=pyproject.toml]
     language: python
     types: [python]
     require_serial: true
     pass_filenames: true
     exclude: '^(docs/)|(examples/)'
