repos:

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    types: [python]
    args: ['-i']
    additional_dependencies: [toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
  - id: mypy
    exclude: '^(docs/)|(examples/)|(utils/fastentrypoints.py)'

- repo: local
  hooks:

  - id: pylint
    name: pylint
    entry: pylint
    types: [file, python]
    language: system
    exclude: '^(docs/)|(examples/)|(utils/fastentrypoints.py)'
