---
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all
build:
    os: ubuntu-22.04
    tools:
        python: '3.11'
    commands:
        - asdf plugin add uv
        - asdf install uv 0.5.2
        - asdf global uv 0.5.2
        - uv venv
        - uv pip install .[docs]
        - . .venv/bin/activate && cd docs && make BUILDDIR=$READTHEDOCS_OUTPUT
